### ISSUE TITLE
Reporting duration in seconds

### ISSUE THREAD

**Issue by rikonor** [census-instrumentation/opencensus-specs#219]
Hi,

This issue pertains to the Go client, although I'd imagine it's probably similar in the spec itself.

Currently, the Go client exposes `UnitMilliseconds`. My impression is that in Census durations should be standardized as `ms`, yet in Prometheus they seem to want to standardize on `seconds` since it is a base unit (See https://prometheus.io/docs/practices/naming/#metric-names).

In the Go client, it's simple enough to add `UnitSeconds = "s"` and everything works as expected, but I wanted to ask if there's a specific reason not to do so?

Thanks,
Or

**Comment by bogdandrutu** [comment]
I understand the motivation of using seconds as a "standard" unit to measure time (everywhere). The main reason we decided to use milliseconds is because >90% of the requests in a micro-service infrastructure will be in the interval [1ms, 999ms] which will be nicer to see. Also modern backends will adjust the unit to be human readable (this can be an argument against my previous point), but some old backends do not have a notion of "unit".

Is your interest mostly in the exported data to Prometheus to be seconds? If that is the case you can wrap the Prometheus exporter and do the conversion to seconds for all the metrics.

**Comment by rikonor** [comment]
I do agree with Prometheus' reasoning for using base units, but assuming this can be worked around by just suffixing the metric name with the units (so in our case `milliseconds`), then I don't see a need to wrap the Prometheus exporter.
