### ISSUE TITLE
Average Aggregation?

### ISSUE THREAD

**Issue by rsalmond** [census-instrumentation/opencensus-specs#256]
I want to implement an average aggregation. Has this been explicitly omitted from opencensus as a design decision?

Or to put it another way, is it worth my time to cut a PR or just DIY what I need for our use case?

**Comment by songy23** [comment]
We used to have a `Mean` aggregation but later we decided to remove it as a design decision, because you can always achieve the same goal by using a `Distribution` aggregation with no histogram. FYI `Distribution` aggregation gives you:
- Average
- Count
- Sum of squared deviations
- Histogram bucket counts (optional)
- Exemplars (optional)

So for your use case I would recommend just use `Distribution` aggregation with no histogram buckets.

**Comment by rsalmond** [comment]
Ah handy, thank you @songy23 I will use that!
