### ISSUE TITLE
Should tag values be less restrictive?

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-specs#53]
Tag values as specified in tags/TagContext.md are as restrictive as keys:

> 
> TagKey
> A string or string wrapper, with some restrictions:
> 
> Must contain only printable ASCII (codes between 32 and 126, inclusive).
> Must have length greater than zero and less than 256.
> TagValue
> A string or string wrapper with the same restrictions as TagKey, except that it is allowed to be empty.
> 

This seems too restrictive. Common metrics backends seem to support arbitrary values:
* https://prometheus.io/docs/concepts/data_model/

Also I would guess that it would be very inconvenient for non-latin languages where you could imagine things like city names being in tag values (for example). I would be very frustrated if the backend I'm using supports my native language characters but I'm forced to encode everything just because OpenCensus creates an artificial restriction.

**Comment by adriancole** [comment]
I suppose this depends on if the intended transport for tags will be easier
for values vs keys. But more importantly tags are propagated, and I'm not
sure there's much prior art on this except a myriad of problems due to
format or size (encoding onto http requests) :P

I think correlation fields certainly can be more flexible than the subset
of which that are propagated. Also not sure if the format isn't too
restrictive, just mentioning the difference.

**Comment by songy23** [comment]
Obsolete.
